version: '3'
services:


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

